### ISSUE TITLE
Por que não foi retornado um array vazio caso o arquivo não exista?

### ISSUE THREAD

**Issue by Maurrici** [ravi2612/Demo1#2]
https://github.com/ravi2612/Demo1/blob/ec95fd29ba147bd1ab6f7611ca0c2dc19b736250/Demo1/Controller.swift#L187

**Comment by ravi2612** [comment]
a função que chama esta na linha 26 da Controller esta tratando retornos nulos . 
 taskList = decodeJSONFile(onDesktopWithFileName: (name ?? null) + null) ?? []
