### ISSUE TITLE
Acredito que neste trecho poderia ser obrigatório que o usuário digitasse algo diferente de uma string vazia 

### ISSUE THREAD

**Issue by Maurrici** [ravi2612/Demo1#3]
https://github.com/ravi2612/Demo1/blob/ec95fd29ba147bd1ab6f7611ca0c2dc19b736250/Demo1/Controller.swift#L20-L23

Quando criei sem nome o arquivo ficou oculto

**Comment by Jwinny** [comment]
Corrigido 
    atualmente se o usuário não colocar um nome, é feito um arquivo default chamado User.json
