### ISSUE TITLE
Fatal Error ao remover task

### ISSUE THREAD

**Issue by rodscesars** [ravi2612/Demo1#4]
![image](https://github.com/ravi2612/Demo1/assets/67443869/a5eae786-228a-4f4d-b92c-a9051ceae773)

Está ocorrendo um erro ao deletar uma task na função removeTask.

**Caso/Sugestão:** Se tiver mais de uma task com title semelhante, a iteração do forEach vai se repetir após a primeira remoção de um item do array de taskList, então ao tentar deletar o próximo item pelo atributo índex, o mesmo índex pode não existir dentro do array.

**Comment by joaocanuto** [comment]
Ademais, Esse problema do remove tá acontecendo também na marcação de concluida da tasks. 
Se voce tem títulos semelhantes, e busca por um padrão presente em ambos títulos, ele modifica de ambos.

**Comment by Jwinny** [comment]
Correção realizada.
