### ISSUE TITLE
Erro em Marcação

### ISSUE THREAD

**Issue by rodscesars** [ravi2612/Demo1#5]
Ao editar uma task na função editTask, está sendo apagado o "[ ]" do title.

<img width="267" alt="Captura de Tela 2023-05-15 às 20 28 26" src="https://github.com/ravi2612/Demo1/assets/67443869/e3d10564-1b8d-400e-bafb-2ad4e90ce5dc">

O mesmo está sendo acrescentado na função isCompleted, quando marcado, porém o título fica em branco. 

<img width="256" alt="Captura de Tela 2023-05-15 às 20 35 50" src="https://github.com/ravi2612/Demo1/assets/67443869/a5de86e4-c334-47a9-b0e3-eefe9021cfad">

**Comment by ravi2612** [comment]
melhoria realizada.
